
---
version: "3.8"
services:
  movies:
    image: dileep97055/paymovies:latest
    ports:
      - 91:80
    deploy:
      replicas: 3
  train:
    image: dileep97055/paytrain:latest
    ports:
      - 92:80
    deploy:
      replicas: 3
  recharge:
    image: dileep97055/payrecharge:latest
    ports:
      - 93:80
    deploy:
      replicas: 3
  dth:
    image: dileep97056/paydth:latest
    ports:
      - 94:80
    deploy:
      replicas: 3

